"""This module contains paths."""
DATABASE_PATH = "src/db.sqlite"
SQL_PATH_FILES = "src/database/sql_files"
TABLES_SQL_PTH = "src/database/sql_files/tables.sql"
IN_GAME_SQL_PATH = "src/database/sql_files/in_game.sql"